"""
End-to-end integration test: Feature A -> Feature B -> Feature D's D1
validation, using REAL recorded output from the actual JS pipeline (not a
hand-typed guess at the contract shape).

The fixture this loads is generated by running the genuine
buildPageData() -> runFeatureB() pipeline on a real sample page (see
mood-classification/manual_tests/record_integration_fixture.js) and saving
the actual Handoff-2 JSON Feature B produces. This test then feeds that
exact payload into validate_profile(), the same function main.py's
/generate endpoint calls on every real request.

This is the "one end-to-end integration test" from the project roadmap's
§5 cross-cutting section -- it would have caught (and did catch, during
development) the fact that Feature B's dedicated D-shaped profile field
(`profile`, added in B's "fix 17") was never actually read by
validate_profile(), which was still preferring the legacy nested
camelCase `musicProfile` field -- silently defaulting content_category,
atmosphere_tags, listening_context, time_of_day, and sensitive_override
on every real request despite B computing real values for all of them.

Regenerate the fixture whenever Feature A's Handoff-1 shape or Feature B's
Handoff-2 shape changes:
    cd mood-classification && node manual_tests/record_integration_fixture.js
"""
import json
import os

import pytest

FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..",
    "mood-classification", "fixtures", "integration_handoff2_sample.json"
)


@pytest.fixture
def real_handoff2():
    if not os.path.exists(FIXTURE_PATH):
        pytest.skip(
            f"Integration fixture not found at {FIXTURE_PATH} -- generate it with: "
            f"cd mood-classification && node manual_tests/record_integration_fixture.js"
        )
    with open(FIXTURE_PATH) as f:
        return json.load(f)


def test_fixture_has_the_shape_this_test_assumes(real_handoff2):
    """Sanity check on the fixture itself, so a failure below points at the
    real bug rather than a stale/malformed fixture."""
    assert "profile" in real_handoff2, "fixture is missing B's fix-17 'profile' field"
    assert "musicProfile" in real_handoff2, "fixture is missing the legacy 'musicProfile' field"
    assert real_handoff2["profile"]["content_category"] != "general", (
        "fixture's sample page should classify as a specific category, not the "
        "generic default -- regenerate the fixture if this page's classification changed"
    )


def test_real_b_profile_flows_through_d1_validate_profile(real_handoff2):
    """
    The core regression test: feeds Feature B's REAL output through
    validate_profile() and asserts the genuinely-computed values survive,
    rather than silently defaulting. Each assertion below failed against
    the pre-fix code (musicProfile was preferred, whose camelCase keys
    don't match MusicProfile's snake_case fields).
    """
    from models import HandoffPayload
    from d1_validate import validate_profile

    payload = HandoffPayload(**real_handoff2)
    profile, prompt_from_b = validate_profile(payload)

    expected = real_handoff2["profile"]

    # Fields that were already working even via the buggy musicProfile path
    # (their names happen to match without underscores) -- confirms this
    # test isn't just trivially passing everything.
    assert profile["mood"] == expected["mood"]
    assert profile["bpm"] == expected["bpm"]
    assert profile["key"] == expected["key"]

    # Fields that were SILENTLY DEFAULTING before this fix -- these are the
    # ones that actually prove the bug is gone, not just that some fields
    # happened to survive by coincidence.
    assert profile["content_category"] == expected["content_category"], (
        "content_category defaulted to 'general' -- the fix-17 profile field "
        "isn't being read (X1's core symptom: every page sounds the same)"
    )
    assert profile["atmosphere_tags"] == expected["atmosphere_tags"]
    assert profile["listening_context"] == expected["listening_context"]
    assert profile["time_of_day"] == expected["time_of_day"]
    assert profile["sensitive_override"] == expected["sensitive_override"]

    # Arousal specifically -- B sends "arousal" on the continuous V-A axis
    # and X1 gave MusicProfile a first-class arousal field, so B's real
    # computed value must survive as arousal rather than being folded into
    # intensity or falling back to the 0.5 default.
    assert profile["arousal"] == pytest.approx(expected["arousal"]), (
        "arousal didn't survive validation -- B's real computed value "
        "should pass through, not fall back to the 0.5 default"
    )
    # ...and it must NOT be written over intensity, which is its own axis
    # and should default independently when B's profile omits it.
    assert profile["intensity"] == pytest.approx(
        expected.get("intensity", 0.5)
    ), "intensity was overwritten by arousal instead of defaulting on its own"

    # The prompt itself should be B's real engineered prompt, not a
    # D-rebuilt fallback (this part of X1 already had a fix landed).
    assert prompt_from_b == real_handoff2["prompt"]


def test_real_b_mood_is_in_ds_valid_taxonomy(real_handoff2):
    """
    Confirms the 11-mood taxonomy alignment between B and D actually holds
    for a real B output, not just in isolation on each side.
    """
    from models import MusicProfile
    mood = real_handoff2["profile"]["mood"]
    # Constructing a MusicProfile with this mood must not trigger the
    # unknown-mood fallback to "neutral".
    profile = MusicProfile(mood=mood)
    assert profile.mood == mood, (
        f"B's real mood '{mood}' isn't in D's valid taxonomy and got "
        f"silently rewritten to '{profile.mood}'"
    )


def test_real_b_profile_builds_a_working_prompt(real_handoff2):
    """The real profile, once validated, should still produce a usable
    prompt via D2 -- confirms the fix doesn't just satisfy the assertions
    above but actually keeps the rest of the pipeline working."""
    from models import HandoffPayload
    from d1_validate import validate_profile
    from d2_prompt import build_prompt

    payload = HandoffPayload(**real_handoff2)
    profile, prompt_from_b = validate_profile(payload)

    prompt = build_prompt(profile, prompt_from_b)
    assert isinstance(prompt, str)
    assert len(prompt) > 20
