"""
Full A -> B -> D pipeline test: takes the REAL recorded Handoff-2 payload
(the actual output of buildPageData() -> runFeatureB(), same fixture
test_integration_handoff.py uses) and drives it through the REAL FastAPI
/generate app end to end -- D1 validate, D2 prompt, D3 generate, D4
post-process, D5 cache -- rather than calling validate_profile()/
build_prompt() directly like test_integration_handoff.py does, or posting a
hand-typed flat dict like test_main_roundtrip.py does.

This is the one gap those two files leave: neither proves that B's real
output survives a trip through the actual HTTP endpoint and comes back as a
playable audio_url with correct metadata. Only D3 (needs a GPU/model) is
mocked, via the same fake MusicGen synthesiser conftest.py installs for the
rest of the suite; D5's cache is faked in-memory the same way
test_main_roundtrip.py does, since the real cache needs a live Postgres/
Supabase. D1, D2, and D4 all run for real.

Regenerate the fixture if Feature A/B's handoff shapes change:
    cd mood-classification && node manual_tests/record_integration_fixture.js

MULTI-PAGE COVERAGE: the single fixture above is one real page (Educational,
mood "curious"). test_real_b_payload_produces_a_playable_clip_end_to_end is
also run, parametrized, against five more real recorded pages covering four
more moods (energetic/tense/calm/sad across Health/News/Emotional
categories) and one adversarial case -- a crisis-support page that B
correctly flags sensitive and silences (mood "silence", isSilent: true,
volume: 0). See mood-classification/fixtures/multi/*.json, generated by
manual_tests/record_integration_fixtures_multi.js. The sensitive-page test
below documents current, real D behaviour on that payload rather than
asserting it's the desired end state -- see its docstring.
"""
import glob
import io
import json
import os
import sys

import numpy as np
import pytest
import soundfile as sf

FIXTURE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..",
    "mood-classification", "fixtures", "integration_handoff2_sample.json"
)

MULTI_FIXTURES_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..",
    "mood-classification", "fixtures", "multi"
)


@pytest.fixture
def real_handoff2():
    if not os.path.exists(FIXTURE_PATH):
        pytest.skip(
            f"Integration fixture not found at {FIXTURE_PATH} -- generate it with: "
            f"cd mood-classification && node manual_tests/record_integration_fixture.js"
        )
    with open(FIXTURE_PATH) as f:
        return json.load(f)


def _load_multi_fixture(name):
    path = os.path.join(MULTI_FIXTURES_DIR, f"{name}.json")
    if not os.path.exists(path):
        pytest.skip(
            f"Integration fixture not found at {path} -- generate it with: "
            f"cd mood-classification && node manual_tests/record_integration_fixtures_multi.js"
        )
    with open(path) as f:
        return json.load(f)


# The four non-sensitive multi-page fixtures -- diverse real moods/categories,
# each recorded from a distinct real page by record_integration_fixtures_multi.js.
DIVERSE_MOOD_FIXTURES = [
    "energetic_fitness",
    "tense_news",
    "calm_meditation",
    "sad_memorial",
]


def _make_wav_bytes(duration_s=6, sr=32000):
    t = np.linspace(0, duration_s, int(sr * duration_s), endpoint=False)
    audio = (0.3 * np.sin(2 * np.pi * 220 * t)).astype(np.float32)
    buf = io.BytesIO()
    sf.write(buf, audio, sr, format="WAV")
    buf.seek(0)
    return buf.read()


@pytest.fixture
def pipeline_client(call_log, monkeypatch):
    """
    Builds a TestClient against the real main.py app with only D3
    (generate_audio) and D5 (cache backend) faked out, same as
    test_main_roundtrip.py's main_client -- D1/D2/D4 run for real against
    whatever real B payload the test posts.
    """
    monkeypatch.setenv("IS_PROD", "false")
    for mod in ("main", "d3_generate", "d5_cache_local", "d5_cache"):
        sys.modules.pop(mod, None)

    import main as main_module

    async def fake_generate_audio(prompt, duration_seconds=28):
        return _make_wav_bytes(duration_s=6), 99

    monkeypatch.setattr(main_module, "generate_audio", fake_generate_audio)

    async def fake_prewarm_cache(*args, **kwargs):
        return None

    monkeypatch.setattr(main_module, "prewarm_cache", fake_prewarm_cache)

    fake_db = {}

    def fake_check_cache(cache_key):
        return fake_db.get(cache_key)

    def fake_save_to_cache(cache_key, clip_bytes, profile, loop_point_ms, gen_time_ms, prompt,
                            seam_discontinuity, prompt_source, generation_seed):
        url = f"fake://{cache_key}"
        fake_db[cache_key] = {
            "cache_key": cache_key,
            "audio_url": url,
            "mood": profile["mood"],
            "bpm": profile["bpm"],
            "key": profile["key"],
            "energy": profile["energy"],
            "valence": profile.get("valence"),
            "arousal": profile.get("arousal"),
            "intensity": profile.get("intensity"),
            "duration_seconds": profile.get("duration_seconds"),
            "style": profile.get("style"),
            "loop_point_ms": loop_point_ms,
            "seam_discontinuity": seam_discontinuity,
            "generation_time_ms": gen_time_ms,
            "prompt_used": prompt,
            "prompt_source": prompt_source,
            "generation_seed": generation_seed,
        }
        return url

    monkeypatch.setattr(main_module, "check_cache", fake_check_cache)
    monkeypatch.setattr(main_module, "save_to_cache", fake_save_to_cache)

    from fastapi.testclient import TestClient
    with TestClient(main_module.app) as client:
        yield client


def test_real_b_payload_produces_a_playable_clip_end_to_end(pipeline_client, real_handoff2):
    """
    The core end-to-end assertion: B's real Handoff-2 payload, posted
    exactly as B would send it, comes back from the real /generate app as
    a cache-miss with a real audio_url and D4's loop metadata -- proving
    D1 (validate) -> D2 (prompt) -> D3 (generate, faked) -> D4 (process)
    -> D5 (cache, faked) all connect correctly on real data, not just each
    stage in isolation.
    """
    response = pipeline_client.post("/generate", json=real_handoff2)

    assert response.status_code == 200
    body = response.json()

    assert body["cache"] == "miss"
    assert body["metadata"]["is_fallback"] is False
    assert body["audio_url"]

    expected = real_handoff2["profile"]
    assert body["metadata"]["mood"] == expected["mood"]
    assert body["metadata"]["bpm"] == expected["bpm"]
    assert body["metadata"]["key"] == expected["key"]

    # D4's loop metadata must have made it all the way through
    assert isinstance(body["metadata"]["loop_point_ms"], int)
    assert body["metadata"]["loop_point_ms"] > 0
    assert "energy_delta_db" in body["metadata"]["seam_discontinuity"]

    # D2 should have used B's real prompt, not rebuilt its own fallback
    assert body["metadata"]["prompt_used"] == real_handoff2["prompt"]
    assert body["metadata"]["prompt_source"] == "feature_b"


def test_real_b_payload_is_cached_on_second_request(pipeline_client, real_handoff2):
    """Posting the same real B payload twice should hit the cache the
    second time, with the same audio_url and loop_point_ms as the first
    (real) generation -- proving make_cache_key() produces a stable key
    from B's actual field values, not just from hand-typed test data."""
    first = pipeline_client.post("/generate", json=real_handoff2).json()
    second = pipeline_client.post("/generate", json=real_handoff2).json()

    assert first["cache"] == "miss"
    assert second["cache"] == "hit"
    assert second["audio_url"] == first["audio_url"]
    assert second["metadata"]["loop_point_ms"] == first["metadata"]["loop_point_ms"]


def test_pipeline_falls_back_gracefully_if_d3_generation_fails_on_real_profile(pipeline_client, real_handoff2, monkeypatch):
    """
    Same real B payload, but D3 (generation) fails -- confirms the
    fallback path (main.py's _fallback_response) still works correctly
    when fed B's real, non-trivial profile shape (nested instruments list,
    long style string, etc.), not just the simple hand-typed profiles the
    other fallback tests use.
    """
    import main as main_module
    from d3_generate import GenerationError

    async def failing_generate_audio(prompt, duration_seconds=28):
        raise GenerationError("simulated model failure")

    monkeypatch.setattr(main_module, "generate_audio", failing_generate_audio)

    def fake_get_fallback_clip(mood):
        return (
            b"fake fallback ogg bytes",
            {"loop_point_ms": 15000, "seam_discontinuity": None,
             "prompt_used": "fake prompt", "generation_seed": 11},
            f"{mood}.ogg",
        )

    monkeypatch.setattr(main_module, "get_fallback_clip", fake_get_fallback_clip)

    response = pipeline_client.post("/generate", json=real_handoff2)

    assert response.status_code == 200
    body = response.json()
    assert body["fallback"] is True
    assert body["metadata"]["is_fallback"] is True
    assert body["metadata"]["mood"] == real_handoff2["profile"]["mood"]
    assert real_handoff2["profile"]["mood"] in body["audio_url"]


@pytest.mark.parametrize("fixture_name", DIVERSE_MOOD_FIXTURES)
def test_diverse_real_pages_produce_playable_clips_end_to_end(pipeline_client, fixture_name):
    """
    Same core end-to-end assertion as
    test_real_b_payload_produces_a_playable_clip_end_to_end, but repeated
    against four more real recorded pages spanning four more moods
    (energetic/Health, tense/News, calm/Health, sad/Emotional) -- the
    single "curious"/Educational fixture above isn't representative of the
    full 11-mood taxonomy, and a D1/D2/D4 bug specific to one mood's field
    values (e.g. an instrument list shape, a BPM range, a style string
    length) could hide behind the one fixture that's actually exercised.
    """
    real_handoff2 = _load_multi_fixture(fixture_name)

    response = pipeline_client.post("/generate", json=real_handoff2)

    assert response.status_code == 200
    body = response.json()

    assert body["cache"] == "miss"
    assert body["metadata"]["is_fallback"] is False
    assert body["audio_url"]

    expected = real_handoff2["profile"]
    assert body["metadata"]["mood"] == expected["mood"]
    assert body["metadata"]["bpm"] == expected["bpm"]
    assert body["metadata"]["key"] == expected["key"]

    assert isinstance(body["metadata"]["loop_point_ms"], int)
    assert body["metadata"]["loop_point_ms"] > 0
    assert "energy_delta_db" in body["metadata"]["seam_discontinuity"]

    assert body["metadata"]["prompt_used"] == real_handoff2["prompt"]
    assert body["metadata"]["prompt_source"] == "feature_b"


def test_sensitive_page_profile_survives_d1_but_d_does_not_honour_bs_silence_flag(pipeline_client):
    """
    Real-life edge case: a crisis-support page that B correctly detects as
    sensitive. B's privacy guarantee already held at recording time (see
    record_integration_fixtures_multi.js -- the LLM mock asserts it's never
    called for this page). B expresses "don't play anything here" via two
    signals on the Handoff-2 envelope: profile.mood == "silence" and a
    top-level isSilent: true / volume: 0.

    This test documents -- deliberately, not as a desired end state -- what
    D actually does with that payload today: D1's mood validator doesn't
    recognise "silence" as one of its 11 valid moods, so it silently
    rewrites it to "neutral" (see models.py's validate_mood) and D proceeds
    to generate ordinary neutral instrumental music. D has no concept of
    B's isSilent/volume signals at all -- HandoffPayload doesn't declare
    those fields, so FastAPI/pydantic just drops them.

    In other words: nothing in Feature D itself stops a crisis page from
    getting background music if whatever calls /generate forwards B's
    Handoff-2 payload without first checking isSilent. That check has to
    live in the caller (the ui/ extension's playback trigger, i.e.
    Feature C) -- which is exactly the still-unwired integration this
    memory's X4 gap refers to. If/when D is asked to also honour
    sensitive_override or isSilent itself, this test's asserted mood should
    change from "neutral" to whatever the new intended behaviour is.
    """
    real_handoff2 = _load_multi_fixture("sensitive_crisis_resource")
    assert real_handoff2["profile"]["mood"] == "silence", (
        "fixture no longer represents the sensitive/silence case -- "
        "regenerate it or update this test"
    )
    assert real_handoff2.get("isSilent") is True
    assert real_handoff2.get("volume") == 0

    response = pipeline_client.post("/generate", json=real_handoff2)

    assert response.status_code == 200
    body = response.json()

    assert body["cache"] == "miss"
    assert body["metadata"]["is_fallback"] is False
    assert body["audio_url"]
    # The actual (current) behaviour: D falls back "silence" to "neutral"
    # and generates real audio -- it does not go quiet.
    assert body["metadata"]["mood"] == "neutral"
    # sensitive_override does survive D1 validation as plain metadata...
    assert real_handoff2["profile"]["sensitive_override"] is True
    # ...but nothing downstream reads it to change behaviour: the response
    # has no field a caller could use to learn "this was sensitive" short
    # of re-deriving it from B's own payload again.
    assert "sensitive_override" not in body["metadata"]
