"""Shared plotting style, statistics and LaTeX emission for the C-01 pipeline.

Two rules encoded here rather than left to each figure:

* percentiles are nearest-rank, never interpolated, and never a bare mean —
  the plan says so in §3 S1 and it matters, because the cache-hit/miss
  distribution is bimodal and a mean over it describes nothing that happened;
* tables are emitted as LaTeX ``booktabs`` and figures as vector PDF, so the
  paper includes the file the script wrote. Hand-retyped numbers are the classic
  way a Results section stops matching its own scripts.
"""

from __future__ import annotations

import math
import random
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

# ── Style ────────────────────────────────────────────────────────────────────
# Sized for a two-column ACM page: 3.33in single column, 7.0in full width.
COL_W = 3.33
FULL_W = 7.0

plt.rcParams.update(
    {
        "figure.dpi": 150,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.02,
        "pdf.fonttype": 42,  # TrueType, not Type 3 — ACM rejects Type 3
        "ps.fonttype": 42,
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans", "Arial", "Helvetica"],
        "font.size": 8,
        "axes.labelsize": 8,
        "axes.titlesize": 8.5,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "legend.fontsize": 7,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "grid.linewidth": 0.5,
        "lines.linewidth": 1.2,
    }
)

# A colourblind-safe qualitative set; index 0 is the shipped system everywhere.
PALETTE = ["#3B6FB6", "#C1651C", "#2E8B6F", "#8E5AA8", "#B03A48", "#6E7486"]
INK = "#14161E"
FAINT = "#6E7486"


# ── Statistics ───────────────────────────────────────────────────────────────
def pct(values, q: float) -> float:
    """Nearest-rank percentile. q in [0, 100]. Never interpolates."""
    xs = sorted(v for v in values if v is not None)
    if not xs:
        return float("nan")
    rank = max(1, math.ceil(q / 100.0 * len(xs)))
    return float(xs[min(rank, len(xs)) - 1])


def summary(values) -> dict:
    xs = [v for v in values if v is not None]
    if not xs:
        return {"n": 0}
    return {
        "n": len(xs),
        "p50": pct(xs, 50),
        "p95": pct(xs, 95),
        "max": float(max(xs)),
        "min": float(min(xs)),
        "mean": sum(xs) / len(xs),
    }


def bootstrap_ci(values, stat=None, resamples: int = 10_000, alpha: float = 0.05, seed: int = 20260810):
    """Percentile bootstrap CI. The plan asks for 10k resamples on p50/p95,
    because a percentile estimated from ~50 samples is noisier than it looks."""
    xs = [v for v in values if v is not None]
    if len(xs) < 2:
        return (float("nan"), float("nan"))
    stat = stat or (lambda s: pct(s, 50))
    rng = random.Random(seed)
    n = len(xs)
    stats = []
    for _ in range(resamples):
        stats.append(stat([xs[rng.randrange(n)] for _ in range(n)]))
    stats.sort()
    lo = stats[max(0, int(alpha / 2 * resamples) - 1)]
    hi = stats[min(resamples - 1, int((1 - alpha / 2) * resamples))]
    return (float(lo), float(hi))


def wilson_ci(successes: int, n: int, z: float = 1.96):
    """Wilson score interval — the right one for a detection rate against the
    50% chance line, because normal-approximation intervals misbehave near the
    bounds and T3 lives or dies on whether the CI contains 0.5."""
    if n == 0:
        return (float("nan"), float("nan"))
    p = successes / n
    d = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / d
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (max(0.0, centre - half), min(1.0, centre + half))


# ── Emission ─────────────────────────────────────────────────────────────────
def save_fig(fig, path: Path) -> None:
    fig.savefig(path.with_suffix(".pdf"))
    fig.savefig(path.with_suffix(".png"))
    plt.close(fig)


def _tex_escape(s: str) -> str:
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("_", r"\_"),
                 ("#", r"\#"), ("$", r"\$"), ("{", r"\{"), ("}", r"\}")):
        s = s.replace(a, b)
    return s


def booktabs(path: Path, caption: str, label: str, header, rows, align: str | None = None,
             notes: str = "") -> None:
    """Emit a LaTeX booktabs table. Numeric columns get siunitx-free tabular
    alignment; we keep it dependency-light so the .tex drops into any preamble
    with only booktabs loaded."""
    align = align or ("l" + "r" * (len(header) - 1))
    lines = [
        "% generated by analysis/build_all.py — do not edit by hand",
        r"\begin{table}[t]",
        r"  \centering",
        r"  \small",
        rf"  \caption{{{caption}}}",
        rf"  \label{{{label}}}",
        rf"  \begin{{tabular}}{{{align}}}",
        r"    \toprule",
        "    " + " & ".join(_tex_escape(str(h)) for h in header) + r" \\",
        r"    \midrule",
    ]
    for row in rows:
        if row is None:
            lines.append(r"    \midrule")
            continue
        lines.append("    " + " & ".join(_tex_escape(str(c)) for c in row) + r" \\")
    lines += [r"    \bottomrule", r"  \end{tabular}"]
    if notes:
        lines.append(rf"  \par\smallskip\footnotesize\raggedright {_tex_escape(notes)}")
    lines += [r"\end{table}", ""]
    path.with_suffix(".tex").write_text("\n".join(lines), encoding="utf-8")


def markdown_table(path: Path, header, rows, notes: str = "") -> None:
    """A readable twin of the .tex, so a reviewer inside the repo can see the
    numbers without a LaTeX run."""
    out = ["| " + " | ".join(str(h) for h in header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    for row in rows:
        if row is None:
            continue
        out.append("| " + " | ".join(str(c) for c in row) + " |")
    if notes:
        out += ["", notes]
    path.with_suffix(".md").write_text("\n".join(out) + "\n", encoding="utf-8")


def fmt(x, places: int = 1, dash: str = "—") -> str:
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return dash
    if isinstance(x, float):
        return f"{x:,.{places}f}"
    return str(x)
